# Generated by Django 2.2.15 on 2020-08-20 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritePosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writeContent', models.TextField(max_length=10000)),
                ('writeTimestamp', models.DateTimeField(auto_now=True)),
                ('writeAuthor', models.CharField(default='anonymous', max_length=255)),
                ('contributer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['writeTimestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClickPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clickImage', models.ImageField(upload_to='media/images/ClickImages')),
                ('clickContent', models.TextField(max_length=10000)),
                ('clickTimestamp', models.DateTimeField(auto_now=True)),
                ('clickAuthor', models.CharField(default='anonymous', max_length=255)),
                ('contributer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photographer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['clickTimestamp'],
            },
        ),
        migrations.CreateModel(
            name='ArtPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artImage', models.ImageField(upload_to='media/images/ArtImages')),
                ('artContent', models.TextField(max_length=10000)),
                ('artTimestamp', models.DateTimeField(auto_now=True)),
                ('artAuthor', models.CharField(default='anonymous', max_length=255)),
                ('contributer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['artTimestamp'],
            },
        ),
    ]
