# Generated by Django 2.2.15 on 2020-08-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artposts',
            name='artAuthor',
        ),
        migrations.RemoveField(
            model_name='clickposts',
            name='clickAuthor',
        ),
        migrations.RemoveField(
            model_name='writeposts',
            name='writeAuthor',
        ),
    ]
